### PR TITLE
Cp rad 528 extension context

### LINKED ISSUE #20: Request from HL7 FHIR-i: tighten the context for the Associated Study Extension
**Section Number** 
[IHE.RAD.IMR\IMR DiagnosticReport Associated Study - FHIR v4.0.1](https://profiles.ihe.net/RAD/IMR/StructureDefinition-associatedStudy.html)

**Issue** 
HL7 FHIR-i is reviewing extensions defined in the FHIR space in order to clean them up, remove redundant extensions and improve the definition of the remaining ones.
During this process, a set of IHE defined extensions where discussed that need work.
One of these extension is the "DiagnosticReport Associated Study" extension. The extension context is 'Element', allowing it to be used on any element on any resource. FHIR-i is concerned that this is far to generic and strongly recommends restricting the use to the specific context where it is intended to be used.

**Proposed Change** 
Restrict the use of these extensions to the root level of `DiagnosticReport`. This can be achieved by adding the line 
`Context: DiagnosticReport` to the header of these extensions in the sushi fsh file.

**Priority**:
- **Medium**: Significant issue or clarification. Requires discussion, but should not lead to long debate.

### PR DESCRIPTION
**Pull request by kinsonho**
Closes #20 

## 📑 Description
Limit the context of the use of associatedStudy extension to be in DiagnosticReport only.

- [ ] Not Completed
- [x] Completed

### CODE REVIEW

**Comment by kinsonho** [comment]
Include some additional tooling updates.

**Comment by lynnfel** [comment]
reviewed

**Review by lynnfel — APPROVED** [review]

**Review by lynnfel — CHANGES_REQUESTED** [review]
At line 296, 
change "- shall support scrolling display requirements as defined RAD TF-1: Section 4.16.4.2.2.5.5 in the Basic Image Review (BIR) supplement." 
to this:
"-shall support scrolling display requirements as defined RAD TF-1: 4.16.4.2.2.5.5 in the Basic Image Review (BIR) Profile"

All other changes look good

**Comment by kinsonho** [comment]
@lynnfel Fixed your latest comment.

**Review by lynnfel — APPROVED** [review]

**Pull request merged**
